### PR TITLE
added scraping campus icon management command

### LINKED ISSUE #339: logos are all the same
# Problem

Currently all logos are the same. (I'm not sure if it is the TVET icon)

# Proposed solutions

- Scrape an logo. 
- or use a more generic placeholder logo.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #339 
This PR made management command for scraping campus icon.
Notes:
- Not all website is still live
- Every website has it's way to show logo, this PR haven't handled all of these
- Some of websites's can't be extracted because logo is hard builded to css (http://www.cput.ac.za/), which is can't be extracted
- Campus that can't be exctracted, it will show default icon

example : getting 'adt' campus
```
getting icon provider 516 from http://www.adt.co.za
raw icon url found = https://www.adt.co.za/wp-content/uploads/2016/08/ADT-logo.svg
icon url found = https://www.adt.co.za/wp-content/uploads/2016/08/ADT-logo.svg
icon downloaded, save it
```
in frontend
selection_005

### CODE REVIEW

**Comment by cchristelis** [comment]
Hi @meomancer, nice work, please move the functionality into utilities. Also add the icon scraping into our 'normal' scrape.

**Comment by meomancer** [comment]
hi @dimasciput 
i can't test it because of saqa website gave timeout

**Comment by cchristelis** [comment]
Hi @dimasciput and @meomancer, have you been able to set up the scrape?

**Comment by cchristelis** [comment]
@meomancer, any progress here?

**Comment by meomancer** [comment]
Can't test it
the page is too slow (gives Request Time Out)
http://ncap.careerhelp.org.za/learningproviders/search/all/page/1

**Comment by dimasciput** [comment]
Hi @meomancer , so this command will scrap campus with their logo, am I correct? Can you create a command to get the logo from campus that already stored in db? So we don't need to scrap the campus again, is that possible?

**Comment by dimasciput** [comment]
I tried to run scrapping_campus command without any added arguments, I only able to get to the page 1, and then it exit.

**Pull request merged**
