### PR TITLE
[WIP] Populate map on load

### LINKED ISSUE #329: Populated map on load
# Problem

When the map is loaded the first time, it seems very empty.

# Proposed solution

Show all results on load.

### PR DESCRIPTION
**Pull request by dimasciput**
this fix #329
Get campuses with pagination, to call the api 

`http://0.0.0.0:63102/api/get-all-campus/?page={page-number}`

It will returns all campus for that page, there will be 50 campuses on one page.

Example results : 

```
{
    "page": 11,
    "current_page": "1",
    "campuses": [
       {
            "campus_location": "-33.91167240000001,18.552253099999987",
            "campus_website": "http://www.northlink.co.za",
            "provider_primary_institution": "Northlink TVET College",
            "campus_popup": "<div class=\"leaflet-header\">\n     <h3>Northlink TVET College</h3>\n</div>\n<div class=\"leaflet-place\">\n    \n        <strong>Campus: Goodwood Campus</strong>\n    \n</div>\n<div class=\"leaflet-content\">\n    <div><i class=\"fa fa-map-marker\"></i> Voortrekker Road </div>\n    <div><i class=\"fa fa-link\"></i> <a href=\"http://www.northlink.co.za\" target=\"_blank\">http://www.northlink.co.za</a> </div>\n    <div><i class=\"fa fa-phone\"></i> N/A</div>\n</div>\n",
            "campus": "Goodwood Campus",
            "campus_is_null": false,
            "campus_location_is_null": false,
            "campus_address": "Voortrekker Road",
            "campus_auto": "Goodwood Campus",
            "long_description": "Northlink TVET College - Goodwood Campus",
            "courses": "['15414, [67109] National Certificate: N1 Engineering Studies', '15443, [67375] National Certificate: N2 Engineering Studies', '4173, [SAQA ID 23253] National Certificate (GETC): Manufacturing, Engineering and Related Activities\\xa0', '2673, [652301] Turner', '2681, [653303] Fitter', '4252, [SAQA ID 49689] National Certificate: Automotive Repair and Maintenance\\xa0', '15517, [67491] National Certificate: N3: Engineering Studies']",
            "courses_is_null": false,
            "campus_provider": "Northlink Tvet College",
            "text": "Goodwood Campus\nNorthlink TVET College - Goodwood Campus\n"
        },, ...
]
```

### CODE REVIEW

**Comment by cchristelis** [comment]
@dimasciput, we are doing this wrong if we transfer all this data during the initial load. 

The initial load for a campus should only have the following:
```
{
    "page": 11,
    "current_page": "1",
    "campuses": [
       {
            "campus_location": "-33.91167240000001,18.552253099999987",
            "courses": "[15414 15443, 4173, 2673, 2681, 4252, 15517]",
            "campus_provider": "Northlink Tvet College",
        },, ...
]
```

FYI @meomancer

**Comment by dimasciput** [comment]
Update the response of get-all-campus to : 

```
    ... 
      {
            "campus_location": "-33.90199780000001,18.638280500000015",
            "campus_provider": "Northlink Tvet College",
            "campus_id": 21,
            "courses_id": "[2425, 2428]",
            "campus": "Head Office"
        },
        {
            "campus_location": "-33.960095200000005,22.455767199999997",
            "campus_provider": "Nqtac Cape (Pty) Ltd",
            "campus_id": 32,
            "courses_id": "[3833, 3840, 3842, 3843, 3846, 3845, 3836, 3837, 3834, 931, 3844]",
            "campus": ""
        },
       ...
```

**Comment by dimasciput** [comment]
@meomancer 
Added api to get courses by ids, 
`/api/get-courses/?ids=15796,15797,15800`

Will returns : 
```
[
    {
        "id": 15796,
        "nlrd": "50440",
        "description": "National Certificate: Vocational, Level 2"
    },
    {
        "id": 15797,
        "nlrd": "50442",
        "description": "National Certificate: Vocational, Level 3"
    },
    {
        "id": 15800,
        "nlrd": "50441",
        "description": "National Certificate: Vocational, Level 4"
    }
]
```

**Comment by cchristelis** [comment]
great @dimasciput, I think we might need to add a view to get the popup message.

**Comment by dimasciput** [comment]
Added api to get campus detail : 
`http://0.0.0.0:63102/api/detail-campus/?id=1405`

Will returns : 
```
{
    "id": 1405,
    "address": "Training Centre Road",
    "phone": "NA",
    "campus": " CN Mahlangu",
    "provider": "Nkangala Tvet College",
    "location": {
        "type": "Point",
        "coordinates": [
            29.0434,
            -25.08253
        ]
    }
}
```

With this information we can create a popup on frontend.

**Comment by cchristelis** [comment]
Let's merge and try it out.

**Comment by meomancer** [comment]
new PR : https://github.com/kartoza/feti/pull/430

**Pull request closed without merging**
