### PR TITLE
Fix Occupation API call.

### LINKED ISSUE #510: Fix Occupation API call.
Currently when the API URL is called it throws a Type Error of the Object being called.

The proposed solution is to explicitly check for the presence of the object being called and make a decision based on the None return value as well.

### PR DESCRIPTION
**Pull request by sonlinux**
Fix #510}

* Check for None value in the query response.

screenshot from 2017-10-20 14 20 18

screenshot from 2017-10-20 14 35 18

### CODE REVIEW

**Comment by cchristelis** [comment]
@sonlinux, I'm expecting to see a list of all occupations, not a blank list. Please update accordingly.

**Comment by sonlinux** [comment]
Alright @cchristelis am updating with some data.

**Comment by cchristelis** [comment]
@sonlinux, please add a screenshot when you have updated.

**Comment by sonlinux** [comment]
Okay @cchristelis, am working on that right now.

**Comment by cchristelis** [comment]
@sonlinux, please push your updates.

**Comment by sonlinux** [comment]
@cchristelis I think I need some help, I still can not figure out why the data is not showing on the API view.
I have the sample data restored in the database, I still do not have it showing on the API or on the search.

**Comment by meomancer** [comment]
hi @sonlinux 
maybe you could disscuss with anita?
she already able to show occupation on API

you need to add parameters q in there
1. check in admin, is there already occupation? take one occupation as reference (for example : Zoologist)
2. check in API : /api/occupation?q=zoo

**Comment by sonlinux** [comment]
Hi @cchristelis I have updated my PR, please review.

**Comment by anitanh** [comment]
Hi @sonlinux maybe you could also add an API to call all available occupations (could be just the name)?

**Comment by sonlinux** [comment]
Great @ann26 , let me open that ticket and I work on it.

**Pull request merged**
