### PR TITLE
User Profile

### PR DESCRIPTION
**Pull request by dimasciput**
Implement #247, #244 
- Add register page
- Add django allauth
- User can view and update their profile
- User can get the travel time based on their location

feti

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer Please review this PR, thanks

**Comment by meomancer** [comment]
@dimasciput nice work in here
my suggestion are :
- rearrange form, put important information in top? name, in top and bio in most bottom?
- could you hide polygon control? because we can't use it
- change location to "my location"? and add a button on map to use geolocation for quick access fr current location? (I think it is related with https://github.com/kartoza/feti/issues/235)

**Comment by dimasciput** [comment]
@meomancer, thank you for the suggestions 
Here's what I added in the last commits : 
- Rearange form
- Hide polygon control
- Change location to "my location"

For the geolocation thing, I will probably do it in another PR. Because it will be tricky to test, they have to run in ssl mode.

**Comment by meomancer** [comment]
LGTM

**Pull request merged**
