### PR TITLE
scraping database

### LINKED ISSUE #202: Occupations: Router
# Problem

The occupations need to be handled in teh front end:

```
// if mode == occupation: highlight "occupation" show the search panel with 'Search for occuption'
   //                                          cover the map with the occupations list. 
   // if results: show learning pathways on results panel and populate map with results pins (numbered by pathway)
```

### LINKED ISSUE #246: Scraping
# Problem

Currently the API's for the courses and campuses offered by the saqa site: http://regqs.saqa.org.za/search.php and the occupations offered by the ncap site:
http://ncap.careerhelp.org.za/occupations
are not available. So until this is available we can only access this data through the page.
# Proposed solution

Let's build a management command that scrapes campuses and courses and their connections from saqa. And a management command that scrapes occupations, learning pathways and the courses.

Perhaps have a look at https://www.crummy.com/software/BeautifulSoup/bs4/doc/

### LINKED ISSUE #252: Occupation Search
After #246 is done, implement occupation search and

### PR DESCRIPTION
**Pull request by meomancer**
this fixes #246 , fixes #202 , fixes #252 

@cchristelis 
the changes :
- changed occupation models a little bit for giving uniqueness to prevent duplicate creates on scraping (just changes if exist)
- scraping course from saqa and campus/occupation from http://ncap.careerhelp.org.za/ (note, not sure where is campus list in saqa)

work list:
- [x] scrap campus and provider from http://ncap.careerhelp.org.za/
- [ ] campus position from http://ncap.careerhelp.org.za/
- [ ] scrap campus and provider from http://regqs.saqa.org.za/search.php
- [x] scrap course from http://regqs.saqa.org.za/search.php
- [x] scrap occupation from http://ncap.careerhelp.org.za/
- [ ] get course that found on step in pathways

Question:
on http://ncap.careerhelp.org.za/learningprovider/726e4609-e72e-4c04-a511-39a196802a1b, there is position of campus that shown on google maps, but doesn't know how to extract this information

on http://regqs.saqa.org.za/search.php, there are several information for course. 
- what is education_training_quality_assurance in saqa?
- what is national_graduate_school_in_education in saqa?
- what is national_certificate_vocational in saqa?

here is screenshots:
screenshot from 2016-09-19 10 17 15
screenshot from 2016-09-19 10 17 23
screenshot from 2016-09-19 10 17 44
screenshot from 2016-09-19 10 17 47
screenshot from 2016-09-19 10 17 55
screenshot from 2016-09-19 10 18 01
screenshot from 2016-09-19 10 18 05
screenshot from 2016-09-19 10 19 24
screenshot from 2016-09-19 10 19 35
screenshot from 2016-09-19 10 19 37

### CODE REVIEW

**Comment by cchristelis** [comment]
Hi @meomancer, the information flow should be courses and campuses/providers and PI's from saqa and only occupation and learning pathways from ncap. Obviously this includes the course learning pathway step connection as well.

**Comment by meomancer** [comment]
@cchristelis do you know where i get campus/provider list from saqa?
I see it on saqa as originator, but i couldn't found where can i get it's detail?

**Comment by dimasciput** [comment]
I think we can merge this one, and continue the rest in another PR. @meomancer Could you update the issue in https://github.com/kartoza/feti/issues/246 with your work list?

**Comment by cchristelis** [comment]
@dimasciput I agree! @meomancer, please merge and run on the live site...

**Comment by meomancer** [comment]
@dimasciput @cchristelis 
updated to show occupation on search
i put on this PR because the commit is already big and i forgot where is the checkpoint :(

this partial fix #202 , #252 

next : router for pathway selection

the demo:
https://drive.google.com/file/d/0B7OxCB3EJZ5ccmdjc19yeXpEa2M/view?usp=sharing

**Comment by dimasciput** [comment]
LGTM, please merge

**Pull request merged**
