### PR TITLE
Advanced search

### PR DESCRIPTION
**Pull request by dimasciput**
List of advanced search query 

- Filter by Field of study, add `&fos={field_of_study id}`
- Filter by SubField of study, add `&sos={field_of_study id}`
- Filter by Qualification type, add `&qt={qualification_type id}`
- Filter by National Qualifications Framework, add `&nqf={national_qualifications_framework id}`
- Filter by National Qualifications Subframework, add `&nqsf={national_qualifications_subframework id}`
- Filter by minimum credits, add `&qt={minimum_credits}`

Get filters : 

- Get all field of study `api/field_of_study`
- Get all subfield of study `api/subfield_of_study`
- Get all qualification type `api/qualification_type`
- Get all National qualifications framework `api/national_qualifications_framework`
- Get all National qualifications subframework `api/national_qualifications_subframework`

### CODE REVIEW

**Comment by dimasciput** [comment]
Advanced Search in campus and course : 

feti

**Comment by dimasciput** [comment]
Add filtered tags and clear filters button.

screenshot from 2017-02-23 16 46 10

**Comment by cchristelis** [comment]
@dimasciput, when choosing where to study, it makes no sense to have minimum credits, public vs private on the other hand makes a lot of sense...

**Comment by dimasciput** [comment]
@cchristelis here's the updated advanced filter in where to study
screen shot 2017-03-07 at 4 18 54 pm

**Pull request merged**
