### PR TITLE
added primary institute admin

### LINKED ISSUE #222: Admin section
# Problem

Some important fields are not yet editable.
# Proposed solution
- [x] A user should be able to update the Primary Institute website. (Question: should users be assigned to these PIs?)
- [ ] A user should be able to update the campus address.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #222 
@cchristelis 

added primary institute admin and it's form
- primary institute admin can edit primary institute and it's provider

screenshot from 2016-09-06 13 34 12
screenshot from 2016-09-06 13 34 26
screenshot from 2016-09-06 13 31 34
screenshot from 2016-09-06 13 31 36
screenshot from 2016-09-06 13 31 42

### CODE REVIEW

**Comment by meomancer** [comment]
Update, changed address on admin

screenshot from 2016-09-08 11 44 07
screenshot from 2016-09-08 11 45 57
screenshot from 2016-09-08 11 45 59
screenshot from 2016-09-08 11 46 10
screenshot from 2016-09-08 11 46 29

screenshot from 2016-09-08 11 52 29
screenshot from 2016-09-08 11 53 20

**Comment by dimasciput** [comment]
Hi @meomancer , I think you should remove `deployment/backups/latest.dmp`, maybe you accidentally push it to github.

**Comment by dimasciput** [comment]
When I tried to open the admin page as a provider official, I got this error message : 

`'NoneType' object has no attribute 'y'`

For this line of code : 

`providers = ProviderSerializer(official.provider.all(), many=True).data`

**Comment by meomancer** [comment]
@dimasciput could you check it again?

**Comment by dimasciput** [comment]
LGTM

**Pull request merged**
