### PR TITLE
Pagination in search (for empty search too)

### LINKED ISSUE #329: Populated map on load
# Problem

When the map is loaded the first time, it seems very empty.

# Proposed solution

Show all results on load.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #329
Hi @dimasciput 
because our PR (https://github.com/kartoza/feti/pull/405) is already too far behind latest code (because embed code), i made this PR and getting important code (also bug fixes) from that PR

### CODE REVIEW

**Comment by dimasciput** [comment]
I don't see the new API in this PR.

**Comment by meomancer** [comment]
@dimasciput yes, instead using new PR, i implemented pagination to our current PR
because basically the PR is same

**Comment by meomancer** [comment]
- [x] pagination on campus 
- [ ] pagination on course
- [ ] pagination on occupation
- [ ] add load more button (now using scroll event)

**Comment by dimasciput** [comment]
Can you merge the old PR to this PR first?

**Comment by meomancer** [comment]
Already merge ol PR to this PR

**Comment by dimasciput** [comment]
Site behavior with this PR : 

feti

**Comment by dimasciput** [comment]
Notes : 
- Remove `<empty>` string in url `http://0.0.0.0:63102/#map/provider/<empty>`
- Marker is not updated when user scrolls to get new campuses
- The courses list is taking a lot of space, I think we can show just a few and add button to see more

**Comment by cchristelis** [comment]
@meomancer and @dimasciput, we can't have a situation where we only get a partial result on any of the sections. I was under the impression the 'scrolling' was going to happen programatically. I.e. that the results are loaded page for page, but without needing any user interaction.

**Pull request closed without merging**
