### PR TITLE
Add text to toggle button

### LINKED ISSUE #445: Show/hide sidebar text update
Rather use "List Results" and "Show Map"

### PR DESCRIPTION
**Pull request by euclidian**
This fixes #445 

image

image

### CODE REVIEW

**Review by dimasciput — COMMENTED** [review]
The font is not matching to the current theme.

**Comment by euclidian** [comment]
Updated screenshot

image

@dimasciput  
But it is behaving strange when clicked, sometimes when we click the <span> inside i tag it doesnt show the result sidebar

**Comment by dimasciput** [comment]
```
But it is behaving strange when clicked, sometimes when we click the inside i tag 
it doesnt show the result sidebar
```

Can you fix it @euclidian ?

**Comment by dimasciput** [comment]
I don't think we need the symbol, you can just remove the `<i>` tag.

**Comment by euclidian** [comment]
Strange behaviour fixed @dimasciput

**Comment by dimasciput** [comment]
Can you remove the symbol too?

**Comment by euclidian** [comment]
updated 

image

image

**Review by dimasciput — APPROVED** [review]
LGTM

**Pull request merged**
