### PR TITLE
added onload and empty search

### LINKED ISSUE #329: Populated map on load
# Problem

When the map is loaded the first time, it seems very empty.

# Proposed solution

Show all results on load.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #329 

hi @cchristelis @dimasciput 
this is new PR for : https://github.com/kartoza/feti/pull/430
because the old PR already to old and so much conflict, so i made new one

- added empty search and onload
- automatically load more after 1 second

i put like 50/521 campuses on top list as indicator. maybe we could give throbber on the right of it?

It is javailable just for provider. should we do it to course?

### CODE REVIEW

**Comment by dimasciput** [comment]
Yes I think we need courses too.

**Comment by cchristelis** [comment]
@dimasciput and @meomancer, let's merge this in and get March's feedback.

**Comment by dimasciput** [comment]
@cchristelis I'll test it first then merge it

**Comment by cchristelis** [comment]
ping @dimasciput, could you please merge this.

**Pull request merged**
