### PR TITLE
All Text in filter data

### LINKED ISSUE #452: All filters in text
# Problem

When I do an area search the criteria for this search is given in the results. It would be great if the same behaviour was also followed with other search items (such as advanced search.

# Proposed Solution

Update​ the search results string above the search results to contain the search criteria.

### PR DESCRIPTION
**Pull request by euclidian**
This supposedly will fixes #452 
Just checking If I'm in the right path @dimasciput @meomancer

### CODE REVIEW

**Comment by dimasciput** [comment]
Hi @euclidian, I think you are on the right track. Please create the filter text like this : 

screen shot 2017-04-02 at 2 21 49 pm

**Comment by euclidian** [comment]
image

I haven't been able to make it as tidy as yours. Can I have your template? @dimasciput

**Comment by euclidian** [comment]
Updated screenshot

image

@dimasciput Should I differentiate what filter is shown based on what tab is currently active? On screenshot above both filters is shown although it is now in provider tab

**Comment by dimasciput** [comment]
@euclidian no need, since now changing to the new tab will clear the search.

**Comment by dimasciput** [comment]
Can you move filter tags closer to the title?

**Comment by dimasciput** [comment]
And remove the filtered label inside the search bar

**Comment by euclidian** [comment]
updated screenshot

image

**Comment by dimasciput** [comment]
@euclidian can you check all advance filter, also create circle and do the search? What is going to look like?

**Comment by euclidian** [comment]
Updated screenshot

image

**Comment by dimasciput** [comment]
@euclidian 
https___cloud_githubusercontent_com_assets_2271663_24684577_3e473ed6-19d1-11e7-9d3e-2d3b96316006_png

**Comment by euclidian** [comment]
updated

image

**Review by dimasciput — APPROVED** [review]
LGTM

**Pull request merged**
