### PR TITLE
Update front page

### PR DESCRIPTION
**Pull request by dimasciput**
- Change carousel images
- Add logo in partner section
- Change logo in top left header

Gif: 

feti

### CODE REVIEW

**Comment by cchristelis** [comment]
@dimasciput, could you add the Ford foundation's logo as well please.

**Comment by dimasciput** [comment]
screen shot 2016-11-28 at 4 39 29 pm

**Comment by dimasciput** [comment]
Partner section:

screen shot 2016-11-28 at 4 46 05 pm

**Comment by cchristelis** [comment]
@dimasciput, the Kartoza and FordFoundation logos seem a little out of place in that they are much higher/much narrower than the others. Perhaps we need to re-arrange and spread over a couple of rows to balance the logos a little. @MariaSolovyeva, do you have any suggestions that you could weigh in here?

**Comment by dimasciput** [comment]
Hi @cchristelis I updated the header and the partner logo section :

header1
header2
partner-section

**Pull request merged**
