### PR TITLE
Update autocomplete

### LINKED ISSUE #290: Update auto complete
From @meomancer :

I get autocomplete, and try one of this, but no result when search
example "ABET TRAINING" for course

and also for campus, could you make provider as autocomplete?
example "University Of Stellenbosch", it is in result, but isn't presented on autocomplete

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #290

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer could you test this? Please rebuild the index first.

**Comment by meomancer** [comment]
@dimasciput 
campus is working fine alongside autocomplete now
but for course, when searching using autocomplete, the result is still 0

example : "U/S: Manufacture of chemically aerated flour confectionery products in a craft bakery environment" from autocomplete

**Comment by dimasciput** [comment]
@meomancer could you try it again, need rebuild index again.

**Comment by meomancer** [comment]
LGTM

**Pull request merged**
