### PR TITLE
Fix date input in all browsers and add tooltip

### LINKED ISSUE #343: Birthdate
# Problem

The format is not easy to guess nor enter without the date picker, which does not show in safari.

# Proposed solution

- Give a calendar popup.
- Give a hint to what the format is.
- Make dob not required.

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #343 

Safari : 
ford_2_-_update_profile-safari

Firefox : 
ford_2_-_update_profile-firefox

### CODE REVIEW

**Comment by cchristelis** [comment]
it looks good, let's make the birthdate not mandatory.

**Comment by dimasciput** [comment]
Fix #341 ( I worked on this PR because they are using same library )

**Comment by cchristelis** [comment]
@marchturnbull, I don't know whether "Filter map by polygon" or "Filter map by circle" are the most accessible labels, do you have a better suggestion?

**Comment by cchristelis** [comment]
@dimasciput, please follow up the tooltip text in another issue and merge this.

**Pull request merged**
